language: node_js
node_js:
- lts/*
branches:
  only:
    - master
git:
  depth: 3
install:
- yarn --frozen-lockfile
script:
- bash ./build.sh
after_success:
- GREN_GITHUB_TOKEN=$GITHUB_TOKEN yarn release
after_script:
- bash ./notify.sh
cache: yarn
deploy:
  on:
    branch: master
    # tags: true
  provider: npm
  email: lishijie519@dingtalk.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
